/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface HifzEntry {
  'id' : bigint,
  'studentId' : bigint,
  'jadeedAyatTo' : bigint,
  'date' : string,
  'createdAt' : Time,
  'juzHaaliMark' : string,
  'notes' : [] | [string],
  'jadeedSurah' : string,
  'jadeedAyatFrom' : bigint,
  'murajaatDetails' : string,
}
export interface HifzEntryInput {
  'jadeedAyatTo' : bigint,
  'date' : string,
  'juzHaaliMark' : string,
  'notes' : [] | [string],
  'jadeedSurah' : string,
  'jadeedAyatFrom' : bigint,
  'murajaatDetails' : string,
}
export interface StudentInput {
  'name' : string,
  'studentClass' : string,
  'section' : string,
  'parentWhatsapp' : string,
}
export interface Student {
  'id' : bigint,
  'name' : string,
  'studentClass' : string,
  'section' : string,
  'parentWhatsapp' : string,
  'createdAt' : Time,
  'parentUserId' : [] | [Principal],
  'teacherId' : Principal,
}
export type Time = bigint;
export interface UserProfile { 'name' : string, 'role' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createHifzEntry' : ActorMethod<
    [
      {
        'studentId' : bigint,
        'jadeedAyatTo' : bigint,
        'date' : string,
        'juzHaaliMark' : string,
        'notes' : [] | [string],
        'jadeedSurah' : string,
        'jadeedAyatFrom' : bigint,
        'murajaatDetails' : string,
      },
    ],
    bigint
  >,
  'createStudent' : ActorMethod<[StudentInput], bigint>,
  'deleteHifzEntry' : ActorMethod<[bigint], undefined>,
  'deleteStudent' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEntriesForStudent' : ActorMethod<[bigint], Array<HifzEntry>>,
  'getHifzEntry' : ActorMethod<[bigint], [] | [HifzEntry]>,
  'getStudent' : ActorMethod<[bigint], [] | [Student]>,
  'getStudentsForParent' : ActorMethod<[], Array<Student>>,
  'getStudentsForTeacher' : ActorMethod<[], Array<Student>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'linkParentToStudent' : ActorMethod<[bigint, Principal], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateHifzEntry' : ActorMethod<[bigint, HifzEntryInput], undefined>,
  'updateStudent' : ActorMethod<[bigint, StudentInput], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];