/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text, 'email' : IDL.Text });
export const TeacherCredential = IDL.Record({
  'email' : IDL.Text,
  'password' : IDL.Text,
  'name' : IDL.Text,
  'claimedBy' : IDL.Opt(IDL.Principal),
});
export const Time = IDL.Int;
export const HifzEntry = IDL.Record({
  'id' : IDL.Nat,
  'studentId' : IDL.Nat,
  'jadeedAyatTo' : IDL.Nat,
  'date' : IDL.Text,
  'createdAt' : Time,
  'juzHaaliMark' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
  'jadeedSurah' : IDL.Text,
  'jadeedAyatFrom' : IDL.Nat,
  'murajaatDetails' : IDL.Text,
});
export const StudentInput = IDL.Record({
  'name' : IDL.Text,
  'studentClass' : IDL.Text,
  'section' : IDL.Text,
  'parentWhatsapp' : IDL.Text,
});
export const Student = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'studentClass' : IDL.Text,
  'section' : IDL.Text,
  'parentWhatsapp' : IDL.Text,
  'createdAt' : Time,
  'parentUserId' : IDL.Opt(IDL.Principal),
  'teacherId' : IDL.Principal,
});
export const StudentWithTeacher = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'studentClass' : IDL.Text,
  'section' : IDL.Text,
  'parentWhatsapp' : IDL.Text,
  'createdAt' : Time,
  'parentUserId' : IDL.Opt(IDL.Principal),
  'teacherId' : IDL.Principal,
  'teacherEmail' : IDL.Text,
  'teacherName' : IDL.Text,
});
export const HifzEntryInput = IDL.Record({
  'jadeedAyatTo' : IDL.Nat,
  'date' : IDL.Text,
  'juzHaaliMark' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
  'jadeedSurah' : IDL.Text,
  'jadeedAyatFrom' : IDL.Nat,
  'murajaatDetails' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'adminDeleteStudent' : IDL.Func([IDL.Nat], [], []),
  'adminGetAllStudents' : IDL.Func([], [IDL.Vec(StudentWithTeacher)], ['query']),
  'adminTransferStudent' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'claimTeacherAccount' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'createHifzEntry' : IDL.Func(
      [
        IDL.Record({
          'studentId' : IDL.Nat,
          'jadeedAyatTo' : IDL.Nat,
          'date' : IDL.Text,
          'juzHaaliMark' : IDL.Text,
          'notes' : IDL.Opt(IDL.Text),
          'jadeedSurah' : IDL.Text,
          'jadeedAyatFrom' : IDL.Nat,
          'murajaatDetails' : IDL.Text,
        }),
      ],
      [IDL.Nat],
      [],
    ),
  'createStudent' : IDL.Func([StudentInput], [IDL.Nat], []),
  'createTeacherCredential' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'deleteHifzEntry' : IDL.Func([IDL.Nat], [], []),
  'deleteStudent' : IDL.Func([IDL.Nat], [], []),
  'deleteTeacherCredential' : IDL.Func([IDL.Text], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEntriesForStudent' : IDL.Func([IDL.Nat], [IDL.Vec(HifzEntry)], ['query']),
  'getHifzEntry' : IDL.Func([IDL.Nat], [IDL.Opt(HifzEntry)], ['query']),
  'getStudent' : IDL.Func([IDL.Nat], [IDL.Opt(Student)], ['query']),
  'getStudentsForParent' : IDL.Func([], [IDL.Vec(Student)], ['query']),
  'getStudentsForTeacher' : IDL.Func([], [IDL.Vec(Student)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'linkParentToStudent' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
  'listTeacherCredentials' : IDL.Func([], [IDL.Vec(TeacherCredential)], ['query']),
  'resetTeacherPassword' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateHifzEntry' : IDL.Func([IDL.Nat, HifzEntryInput], [], []),
  'updateStudent' : IDL.Func([IDL.Nat, StudentInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text, 'email' : IDL.Text });
  const TeacherCredential = IDL.Record({
    'email' : IDL.Text,
    'password' : IDL.Text,
    'name' : IDL.Text,
    'claimedBy' : IDL.Opt(IDL.Principal),
  });
  const Time = IDL.Int;
  const HifzEntry = IDL.Record({
    'id' : IDL.Nat,
    'studentId' : IDL.Nat,
    'jadeedAyatTo' : IDL.Nat,
    'date' : IDL.Text,
    'createdAt' : Time,
    'juzHaaliMark' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
    'jadeedSurah' : IDL.Text,
    'jadeedAyatFrom' : IDL.Nat,
    'murajaatDetails' : IDL.Text,
  });
  const StudentInput = IDL.Record({
    'name' : IDL.Text,
    'studentClass' : IDL.Text,
    'section' : IDL.Text,
    'parentWhatsapp' : IDL.Text,
  });
  const Student = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'studentClass' : IDL.Text,
    'section' : IDL.Text,
    'parentWhatsapp' : IDL.Text,
    'createdAt' : Time,
    'parentUserId' : IDL.Opt(IDL.Principal),
    'teacherId' : IDL.Principal,
  });
  const StudentWithTeacher = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'studentClass' : IDL.Text,
    'section' : IDL.Text,
    'parentWhatsapp' : IDL.Text,
    'createdAt' : Time,
    'parentUserId' : IDL.Opt(IDL.Principal),
    'teacherId' : IDL.Principal,
    'teacherEmail' : IDL.Text,
    'teacherName' : IDL.Text,
  });
  const HifzEntryInput = IDL.Record({
    'jadeedAyatTo' : IDL.Nat,
    'date' : IDL.Text,
    'juzHaaliMark' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
    'jadeedSurah' : IDL.Text,
    'jadeedAyatFrom' : IDL.Nat,
    'murajaatDetails' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'adminDeleteStudent' : IDL.Func([IDL.Nat], [], []),
    'adminGetAllStudents' : IDL.Func([], [IDL.Vec(StudentWithTeacher)], ['query']),
    'adminTransferStudent' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'claimTeacherAccount' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'createHifzEntry' : IDL.Func(
        [
          IDL.Record({
            'studentId' : IDL.Nat,
            'jadeedAyatTo' : IDL.Nat,
            'date' : IDL.Text,
            'juzHaaliMark' : IDL.Text,
            'notes' : IDL.Opt(IDL.Text),
            'jadeedSurah' : IDL.Text,
            'jadeedAyatFrom' : IDL.Nat,
            'murajaatDetails' : IDL.Text,
          }),
        ],
        [IDL.Nat],
        [],
      ),
    'createStudent' : IDL.Func([StudentInput], [IDL.Nat], []),
    'createTeacherCredential' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'deleteHifzEntry' : IDL.Func([IDL.Nat], [], []),
    'deleteStudent' : IDL.Func([IDL.Nat], [], []),
    'deleteTeacherCredential' : IDL.Func([IDL.Text], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEntriesForStudent' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(HifzEntry)],
        ['query'],
      ),
    'getHifzEntry' : IDL.Func([IDL.Nat], [IDL.Opt(HifzEntry)], ['query']),
    'getStudent' : IDL.Func([IDL.Nat], [IDL.Opt(Student)], ['query']),
    'getStudentsForParent' : IDL.Func([], [IDL.Vec(Student)], ['query']),
    'getStudentsForTeacher' : IDL.Func([], [IDL.Vec(Student)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'linkParentToStudent' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
    'listTeacherCredentials' : IDL.Func([], [IDL.Vec(TeacherCredential)], ['query']),
    'resetTeacherPassword' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateHifzEntry' : IDL.Func([IDL.Nat, HifzEntryInput], [], []),
    'updateStudent' : IDL.Func([IDL.Nat, StudentInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };
