/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface HifzEntryInput {
    jadeedAyatTo: bigint;
    date: string;
    juzHaaliMark: string;
    notes?: string;
    jadeedSurah: string;
    jadeedAyatFrom: bigint;
    murajaatDetails: string;
}
export type Time = bigint;
export interface HifzEntry {
    id: bigint;
    studentId: bigint;
    jadeedAyatTo: bigint;
    date: string;
    createdAt: Time;
    juzHaaliMark: string;
    notes?: string;
    jadeedSurah: string;
    jadeedAyatFrom: bigint;
    murajaatDetails: string;
}
export interface UserProfile {
    name: string;
    role: string;
    email: string;
}
export interface Student {
    id: bigint;
    name: string;
    studentClass: string;
    section: string;
    parentWhatsapp: string;
    createdAt: Time;
    parentUserId?: Principal;
    teacherId: Principal;
}
export interface StudentWithTeacher {
    id: bigint;
    name: string;
    studentClass: string;
    section: string;
    parentWhatsapp: string;
    createdAt: Time;
    parentUserId?: Principal;
    teacherId: Principal;
    teacherEmail: string;
    teacherName: string;
}
export interface TeacherCredential {
    email: string;
    password: string;
    name: string;
    claimedBy?: Principal;
}
export interface StudentInput {
    name: string;
    studentClass: string;
    section: string;
    parentWhatsapp: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createHifzEntry(input: {
        studentId: bigint;
        jadeedAyatTo: bigint;
        date: string;
        juzHaaliMark: string;
        notes?: string;
        jadeedSurah: string;
        jadeedAyatFrom: bigint;
        murajaatDetails: string;
    }): Promise<bigint>;
    createStudent(input: StudentInput): Promise<bigint>;
    deleteHifzEntry(entryId: bigint): Promise<void>;
    deleteStudent(studentId: bigint): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getEntriesForStudent(studentId: bigint): Promise<Array<HifzEntry>>;
    getHifzEntry(entryId: bigint): Promise<HifzEntry | null>;
    getStudent(studentId: bigint): Promise<Student | null>;
    getStudentsForParent(): Promise<Array<Student>>;
    getStudentsForTeacher(): Promise<Array<Student>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    linkParentToStudent(studentId: bigint, parentUserId: Principal): Promise<void>;
    adminDeleteStudent(studentId: bigint): Promise<void>;
    adminGetAllStudents(): Promise<Array<StudentWithTeacher>>;
    adminTransferStudent(studentId: bigint, targetTeacherEmail: string): Promise<void>;
    claimTeacherAccount(email: string, password: string): Promise<void>;
    createTeacherCredential(email: string, password: string, name: string): Promise<void>;
    deleteTeacherCredential(email: string): Promise<void>;
    listTeacherCredentials(): Promise<Array<TeacherCredential>>;
    resetTeacherPassword(email: string, newPassword: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateHifzEntry(entryId: bigint, input: HifzEntryInput): Promise<void>;
    updateStudent(studentId: bigint, input: StudentInput): Promise<void>;
}
import type { HifzEntry as _HifzEntry, HifzEntryInput as _HifzEntryInput, Student as _Student, StudentWithTeacher as _StudentWithTeacher, TeacherCredential as _TeacherCredential, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createHifzEntry(arg0: {
        studentId: bigint;
        jadeedAyatTo: bigint;
        date: string;
        juzHaaliMark: string;
        notes?: string;
        jadeedSurah: string;
        jadeedAyatFrom: bigint;
        murajaatDetails: string;
    }): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createHifzEntry(to_candid_record_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createHifzEntry(to_candid_record_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createStudent(arg0: StudentInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createStudent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createStudent(arg0);
            return result;
        }
    }
    async deleteHifzEntry(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteHifzEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteHifzEntry(arg0);
            return result;
        }
    }
    async deleteStudent(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStudent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStudent(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEntriesForStudent(arg0: bigint): Promise<Array<HifzEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEntriesForStudent(arg0);
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEntriesForStudent(arg0);
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHifzEntry(arg0: bigint): Promise<HifzEntry | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getHifzEntry(arg0);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHifzEntry(arg0);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudent(arg0: bigint): Promise<Student | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudent(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudent(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudentsForParent(): Promise<Array<Student>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentsForParent();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentsForParent();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudentsForTeacher(): Promise<Array<Student>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentsForTeacher();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentsForTeacher();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async linkParentToStudent(arg0: bigint, arg1: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.linkParentToStudent(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.linkParentToStudent(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateHifzEntry(arg0: bigint, arg1: HifzEntryInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateHifzEntry(arg0, to_candid_HifzEntryInput_n17(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateHifzEntry(arg0, to_candid_HifzEntryInput_n17(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateStudent(arg0: bigint, arg1: StudentInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStudent(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStudent(arg0, arg1);
            return result;
        }
    }
    async adminDeleteStudent(arg0: bigint): Promise<void> {
        if (this.processError) {
            try { return await this.actor.adminDeleteStudent(arg0); } catch (e) { this.processError(e); throw new Error("unreachable"); }
        } else { return await this.actor.adminDeleteStudent(arg0); }
    }
    async adminGetAllStudents(): Promise<Array<StudentWithTeacher>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetAllStudents();
                return result.map((v) => from_candid_StudentWithTeacher(v));
            } catch (e) { this.processError(e); throw new Error("unreachable"); }
        } else {
            const result = await this.actor.adminGetAllStudents();
            return result.map((v) => from_candid_StudentWithTeacher(v));
        }
    }
    async adminTransferStudent(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try { return await this.actor.adminTransferStudent(arg0, arg1); } catch (e) { this.processError(e); throw new Error("unreachable"); }
        } else { return await this.actor.adminTransferStudent(arg0, arg1); }
    }
    async claimTeacherAccount(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try { return await this.actor.claimTeacherAccount(arg0, arg1); } catch (e) { this.processError(e); throw new Error("unreachable"); }
        } else { return await this.actor.claimTeacherAccount(arg0, arg1); }
    }
    async createTeacherCredential(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try { return await this.actor.createTeacherCredential(arg0, arg1, arg2); } catch (e) { this.processError(e); throw new Error("unreachable"); }
        } else { return await this.actor.createTeacherCredential(arg0, arg1, arg2); }
    }
    async deleteTeacherCredential(arg0: string): Promise<void> {
        if (this.processError) {
            try { return await this.actor.deleteTeacherCredential(arg0); } catch (e) { this.processError(e); throw new Error("unreachable"); }
        } else { return await this.actor.deleteTeacherCredential(arg0); }
    }
    async listTeacherCredentials(): Promise<Array<TeacherCredential>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTeacherCredentials();
                return result.map((v) => from_candid_TeacherCredential(v));
            } catch (e) { this.processError(e); throw new Error("unreachable"); }
        } else {
            const result = await this.actor.listTeacherCredentials();
            return result.map((v) => from_candid_TeacherCredential(v));
        }
    }
    async resetTeacherPassword(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try { return await this.actor.resetTeacherPassword(arg0, arg1); } catch (e) { this.processError(e); throw new Error("unreachable"); }
        } else { return await this.actor.resetTeacherPassword(arg0, arg1); }
    }
}
function from_candid_StudentWithTeacher(value: _StudentWithTeacher): StudentWithTeacher {
    return {
        id: value.id,
        name: value.name,
        studentClass: value.studentClass,
        section: value.section,
        parentWhatsapp: value.parentWhatsapp,
        createdAt: value.createdAt,
        parentUserId: value.parentUserId.length === 0 ? undefined : value.parentUserId[0],
        teacherId: value.teacherId,
        teacherEmail: value.teacherEmail,
        teacherName: value.teacherName,
    };
}
function from_candid_TeacherCredential(value: _TeacherCredential): TeacherCredential {
    return {
        email: value.email,
        password: value.password,
        name: value.name,
        claimedBy: value.claimedBy.length === 0 ? undefined : value.claimedBy[0],
    };
}
function from_candid_HifzEntry_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HifzEntry): HifzEntry {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Student_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Student): Student {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_HifzEntry]): HifzEntry | null {
    return value.length === 0 ? null : from_candid_HifzEntry_n8(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Student]): Student | null {
    return value.length === 0 ? null : from_candid_Student_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    studentClass: string;
    section: string;
    parentWhatsapp: string;
    createdAt: _Time;
    parentUserId: [] | [Principal];
    teacherId: Principal;
}): {
    id: bigint;
    name: string;
    studentClass: string;
    section: string;
    parentWhatsapp: string;
    createdAt: Time;
    parentUserId?: Principal;
    teacherId: Principal;
} {
    return {
        id: value.id,
        name: value.name,
        studentClass: value.studentClass,
        section: value.section,
        parentWhatsapp: value.parentWhatsapp,
        createdAt: value.createdAt,
        parentUserId: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.parentUserId)),
        teacherId: value.teacherId
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    studentId: bigint;
    jadeedAyatTo: bigint;
    date: string;
    createdAt: _Time;
    juzHaaliMark: string;
    notes: [] | [string];
    jadeedSurah: string;
    jadeedAyatFrom: bigint;
    murajaatDetails: string;
}): {
    id: bigint;
    studentId: bigint;
    jadeedAyatTo: bigint;
    date: string;
    createdAt: Time;
    juzHaaliMark: string;
    notes?: string;
    jadeedSurah: string;
    jadeedAyatFrom: bigint;
    murajaatDetails: string;
} {
    return {
        id: value.id,
        studentId: value.studentId,
        jadeedAyatTo: value.jadeedAyatTo,
        date: value.date,
        createdAt: value.createdAt,
        juzHaaliMark: value.juzHaaliMark,
        notes: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.notes)),
        jadeedSurah: value.jadeedSurah,
        jadeedAyatFrom: value.jadeedAyatFrom,
        murajaatDetails: value.murajaatDetails
    };
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Student>): Array<Student> {
    return value.map((x)=>from_candid_Student_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_HifzEntry>): Array<HifzEntry> {
    return value.map((x)=>from_candid_HifzEntry_n8(_uploadFile, _downloadFile, x));
}
function to_candid_HifzEntryInput_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: HifzEntryInput): _HifzEntryInput {
    return to_candid_record_n18(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    jadeedAyatTo: bigint;
    date: string;
    juzHaaliMark: string;
    notes?: string;
    jadeedSurah: string;
    jadeedAyatFrom: bigint;
    murajaatDetails: string;
}): {
    jadeedAyatTo: bigint;
    date: string;
    juzHaaliMark: string;
    notes: [] | [string];
    jadeedSurah: string;
    jadeedAyatFrom: bigint;
    murajaatDetails: string;
} {
    return {
        jadeedAyatTo: value.jadeedAyatTo,
        date: value.date,
        juzHaaliMark: value.juzHaaliMark,
        notes: value.notes ? candid_some(value.notes) : candid_none(),
        jadeedSurah: value.jadeedSurah,
        jadeedAyatFrom: value.jadeedAyatFrom,
        murajaatDetails: value.murajaatDetails
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    studentId: bigint;
    jadeedAyatTo: bigint;
    date: string;
    juzHaaliMark: string;
    notes?: string;
    jadeedSurah: string;
    jadeedAyatFrom: bigint;
    murajaatDetails: string;
}): {
    studentId: bigint;
    jadeedAyatTo: bigint;
    date: string;
    juzHaaliMark: string;
    notes: [] | [string];
    jadeedSurah: string;
    jadeedAyatFrom: bigint;
    murajaatDetails: string;
} {
    return {
        studentId: value.studentId,
        jadeedAyatTo: value.jadeedAyatTo,
        date: value.date,
        juzHaaliMark: value.juzHaaliMark,
        notes: value.notes ? candid_some(value.notes) : candid_none(),
        jadeedSurah: value.jadeedSurah,
        jadeedAyatFrom: value.jadeedAyatFrom,
        murajaatDetails: value.murajaatDetails
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
